#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
BIN=/root/testlim/console_config.sh

boot() {
    echo "checking for onion.console.install=2"
    $BIN -console_install
}

start_service() {
    procd_open_instance
    procd_set_param file /etc/config/onion
    procd_set_param command $BIN -v

    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger onion
    echo "service_triggers for onion.test"
   # $BIN -v
}



reload_service() {
    echo "Explicitly restarting service"
    echo "calling console_config"
    mkdir /root/testlim/test/
    nothing=$($BIN -v)
}
